### ISSUE TITLE
Type '"esm"' is not assignable

### ISSUE THREAD

**Issue by nickray** [open-source-labs/vno#110]
Hi, I'm trying to set this up (on Arch Linux, latest everything from official repositories). This is what I get:

```
% deno install --reload --allow-net --unstable https://deno.land/x/vno/install/vno.ts
Download https://deno.land/x/vno/install/vno.ts
Warning Implicitly using latest version (v1.2.2) for https://deno.land/x/vno/install/vno.ts
Download https://deno.land/x/vno@v1.2.2/install/vno.ts
(...)
Download https://esm.sh/v41/node_process.js
Check https://deno.land/x/vno/install/vno.ts
error: TS2322 [ERROR]: Type '"esm"' is not assignable to type '"module" | "classic" | undefined'.
        bundle: "esm",
        ~~~~~~
    at https://deno.land/x/vno@v1.2.2/core/lib/resolver.ts:131:9
```

Any pointers?

**Comment by edify42** [comment]
I get the same thing - is it related to the latest release of `deno`?

```bash
Check https://deno.land/x/vno/install/vno.ts
error: TS2322 [ERROR]: Type '"esm"' is not assignable to type '"module" | "classic" | undefined'.
        bundle: "esm",
        ~~~~~~
    at https://deno.land/x/vno@v1.2.2/core/lib/resolver.ts:131:9
root@12caf9b8123c:~#
root@12caf9b8123c:~# deno --version
deno 1.10.1 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.27
typescript 4.2.2
```

**Comment by greenya** [comment]
Getting same error. Any update on this issue?

**Comment by unknownbreaker** [comment]
@edify42 You might be correct that it's related to the Deno 1.10.x's API change. `esm` is no longer a supported value for the bundle emit option, but is now `module` or `classic`. 1.9.x used `esm`.
https://deno.land/manual@v1.10.0/typescript/runtime

**Comment by Ericarthurc** [comment]
Same error

**Comment by buttercubz** [comment]
@unknownbreaker The pr that fixes is already here, in the same way a release must be created so that it is available in deno.land

CC @Ericarthurc @greenya @edify42 @nickray

**Comment by jgrubb16** [comment]
If you are still having issues using the install script, for now, use:

`deno install --allow-net --unstable -f https://deno.land/x/vno@v1.3.1/install/vno.ts`
