### ISSUE TITLE
create command fails under deno v.1.12.2 due to incompatible std library

### ISSUE THREAD

**Issue by bosam** [open-source-labs/vno#124]
Hi,
When running vno create under deno 1.12.2 and vno 1.4.3 on a fresh install on Mac OS Catalina and Windows 10,
an error occurs:

> Are you creating a universal app(SSG/SSR) or spa(Single Page App)? [universal/spa] spa
 error: Uncaught (in promise) TypeError: Must be a file URL.
    throw new TypeError("Must be a file URL.");
          ^
    at Module.fromFileUrl (https://deno.land/std@0.83.0/path/posix.ts:484:11)
    at create (https://deno.land/x/vno@v1.4.1/core/cli/commands.ts:47:27)
    at async main (https://deno.land/x/vno@v1.4.1/install/vno.ts:31:36)

This is due to a incompatibility with std 0.83 which changes the way path.fromFileUrl expects a parameter.

A P.R. has been created which upgrades the deps.ts file for that component to 0.98.0 as stated in another P.R which did the exact same thing but forgot about this part of the library.

**Comment by adxzhang1** [comment]
We removed those lines in v1.4.3, those error logs are showing for v1.4.1. Could you try using vno with https://deno.land/x/vno@v1.4.3/install/vno.ts?

**Comment by bosam** [comment]
It works with specifying that version now 🤔 
I have been stuck since last week with that issue. I even cleared the whole cache and re-installed vno following the README instructions and still had that issue happening.

Could it be that my install script was still pulling the previous version?
Once I forked it and created that change the whole command started working as expected.

That's great to hear that you removed these deps here, as I like deno's approach to dependencies but due to how fast the code evolves it also forces us to update fast.

Do what you will with the P.R. and this ticket, thanks for the help!

**Comment by adxzhang1** [comment]
Awesome! We also had that issue where it was pulling previous versions from deno.land. May be an issue with how things are getting cached.
