### ISSUE TITLE
Separate vno compiler from vno cli (suggestion)

### ISSUE THREAD

**Issue by RivierGrullon** [open-source-labs/vno#65]
With this I mean create a refactor how the cli is build.

The command line should be agnostic about how the proccess are made I mean main file "vno.ts" includes all the code like the how the server should run, how the components should be created and how the files should be compiled.

For more scalability will be better separate those functionality because in the future will be more easy to add more functionality to the command line.

(sorry for my english, is not my first language)

**Comment by NervousNerve** [comment]
I agree. Having some main script to handle and customize initialization would be good.
Right now, I can not figure out how to include plugins like VueRouter or Vuex.

**Comment by buttercubz** [comment]
> With this I mean create a refactor how the cli is build.
> 
> The command line should be agnostic about how the proccess are made I mean main file "vno.ts" includes all the code like the how the server should run, how the components should be created and how the files should be compiled.
> 
> For more scalability will be better separate those functionality because in the future will be more easy to add more functionality to the command line.
> 
> (sorry for my english, is not my first language)

I agree to separate the entire compiler from the cli in general, also to look for a way that preprocessors and third-party plugins can be integrated more easily

**Comment by andrew-rehrig** [comment]
just an update on this :: a lot of these issues are addressed in the newest release. 

we're still working on it :: i'm going to close this issue for now; feel free to open a new issue with other specific concerns

Thanks!!
