### ISSUE TITLE
about hot-reload, plans to creating that?

### ISSUE THREAD

**Issue by SamukaDEV** [open-source-labs/vno#76]
support or creation, i think users will ask about these things soon!

or how we can implement this feature, if already have a way to do it outside VNO?!

**Comment by buttercubz** [comment]
> support or creation, i think users will ask about these things soon!
> 
> or how we can implement this feature, if already have a way to do it outside VNO?!

sure i'm thinking to include this

**Comment by SamukaDEV** [comment]
nice!! and thanks!
