### ISSUE TITLE
main Readme and src/Readme aren't synced

### ISSUE THREAD

**Issue by Tzahile** [open-source-labs/vno#77]
I tried installing `Vno` using Deno < 1.7, and after it failed I wondered if you mention anything about minimum-version requirements.
I found in `src` the last PR changed `Deno.compile` into `Deno.emit` **and stated version >= 1.7 is required**.

Nevertheless, the main Readme file remained unchanged.
I think it's best to remove the `src/Readme` to prevent future confusions.
I'm opening a PR regarding this for your ease.

Thanks for the effort, I'm looking forward to see Vno project grow!

**Comment by andrew-rehrig** [comment]
Thanks for the issue! I've updated the readMe to reflect the current version, but we prefer to keep both files.
