### ISSUE TITLE
The default svg template is down.

### ISSUE THREAD

**Issue by RivierGrullon** [open-source-labs/vno#81]
[Vno svg](https://svgshare.com/i/SNz.svg) 

I tried to create a new vno app and when I start the server the svg was down 
![image](https://user-images.githubusercontent.com/45011060/106346726-705e3680-628f-11eb-978d-3d76d3e867e4.png)
![image](https://user-images.githubusercontent.com/45011060/106346737-79e79e80-628f-11eb-9f09-906394deda06.png)

**Comment by jgrubb16** [comment]
We aren't seeing any svg issues on our end. Could you try reinstalling and make sure you're running the latest version? 

deno install --allow-read --allow-write --allow-run --allow-net --unstable -f -n vno https://deno.land/x/vno/install/vno.ts

**Comment by RivierGrullon** [comment]
Yes, I'm running the last version of vno, idk but when I post the issue the svg wasn't working but now works lol
