### ISSUE TITLE
List Vue versions supported 

### ISSUE THREAD

**Issue by MichaelCurrin** [open-source-labs/vno#85]
I saw here 

https://github.com/open-source-labs/vno/blob/main/src/lib/defaults.ts

That Vue 2 is in use. My guess is that Vue 3 might not be supported here.

It would be useful to make that clear on readme. Such as with a badge that says

vue - 2.x

**Comment by andrew-rehrig** [comment]
We've just released a version that allows the use of either Vue v2.6.12 or Vue v3.0.5

This change has been reflected in the ReadMe :: if a version isn't specified vno will default to use 2.6.12

Thanks!

**Comment by MichaelCurrin** [comment]
Ok great thanks
