### ISSUE TITLE
problems compiling vno 

### ISSUE THREAD

**Issue by pdenapo** [open-source-labs/vno#91]
I have tried to install vno, following the instructions on the page. I'm using deno 1.7.5

$ deno --version
deno 1.7.5 (release, x86_64-unknown-linux-gnu)
v8 9.0.123
typescript 4.1.4

$deno install --allow-net --unstable https://deno.land/x/vno/install/vno.ts

error: TS2673 [ERROR]: Constructor of class 'Factory' is private and only accessible within the class declaration.
  const vno = new Factory();
              ~~~~~~~~~~~~~
    at https://deno.land/x/vno@v1.2.0/core/cli/commands.ts:27:15

TS2673 [ERROR]: Constructor of class 'Factory' is private and only accessible within the class declaration.
  const vno = new Factory();
              ~~~~~~~~~~~~~
    at https://deno.land/x/vno@v1.2.0/core/cli/commands.ts:37:15

Found 2 errors.

**Comment by Rakhmadi** [comment]
try this:
```
deno install --allow-net --unstable https://raw.githubusercontent.com/open-source-labs/vno/main/install/vno.ts
```
this worked for me
```
deno 1.7.5 (release, x86_64-pc-windows-msvc)
v8 9.0.123
typescript 4.1.4
```

**Comment by mggower** [comment]
This should be fixed, overlooked detail on my part, sorry bout that
