### ISSUE TITLE
vno run dev reload not detecting changes on Windows

### ISSUE THREAD

**Issue by perezd** [open-source-labs/vno#95]
Platform: Windows 10
Deno version: 1.8.0
Vno version: 1.2.1

ran: `vno run dev`

and the first run compiled/displayed as expected, however, any subsequent edits do not seem to be reflected, even when I reload the browser.

If I edit the index.html template in public/ that updates on reload, but nothing related to .vue files seems to update while dev is running.

No observable errors in browser console.

**Comment by andrew-rehrig** [comment]
Hi there! As it currently stands, the dev server is just a barebones server to render your front end. We’re working on making the dev server hot, but in the meantime you’ll need to rebuild to see your changes reflected in the browser.

**Comment by perezd** [comment]
Oh ok, I think the README made it seem like that would happen.
