### ISSUE TITLE
dependency 'vue-deno-compiler' fails at runtime

### ISSUE THREAD

**Issue by mggower** [open-source-labs/vno#96]
`error: Uncaught SyntaxError: The requested module 'https://cdn.esm.sh/v15/_node_fs.js' does not provide an export named 'default'
import __fs$ from "https://cdn.esm.sh/v15/_node_fs.js";
       ~~~~~
    at <anonymous> (https://raw.githubusercontent.com/crewdevio/vue-deno-compiler/master/src/postcss/postcss.js:6:8)`

**Comment by buttercubz** [comment]
https://github.com/crewdevio/vue-deno-compiler/issues/4#issuecomment-795797955

**Comment by buttercubz** [comment]
https://github.com/postui/esm.sh/issues/27#issuecomment-793797238

**Comment by buttercubz** [comment]
I am working to create a local version([vue-deno-compiler](https://github.com/crewdevio/vue-deno-compiler)) that does not use dependencies that we cannot control directly

**Comment by ije** [comment]
in fact in latest update, esm.sh can build vue's sfc compiler

```js
import { parse } from 'https://esm.sh/@vue/compiler-sfc'
```

**Comment by ije** [comment]
@mggower since esm.sh has switched deno polyfills to `std/node`, in deno app the old polyfill would not work, please clean your deno cache: `deno --reload`

**Comment by vincent-olivert-riera** [comment]
So, what's the recommended way for installing `vno` right now? The official way (from https://deno.land/x/vno@v1.2.1) fails for me:

```
$ deno install --allow-net --unstable https://deno.land/x/vno/install/vno.ts
[snip]
error: Uncaught SyntaxError: The requested module 'https://cdn.esm.sh/v15/_node_fs.js' does not provide an export named 'default'
import __fs$ from "https://cdn.esm.sh/v15/_node_fs.js";
       ~~~~~
    at <anonymous> (https://raw.githubusercontent.com/crewdevio/vue-deno-compiler/master/src/postcss/postcss.js:6:8)
```

**Comment by ije** [comment]
@vincent-olivert-riera 
deno install --allow-net --reload --unstable https://deno.land/x/vno/install/vno.ts

**Comment by vincent-olivert-riera** [comment]
> @vincent-olivert-riera
> deno install --allow-net --reload --unstable https://deno.land/x/vno/install/vno.ts

`--reload`? Why? This is a brand new installation. The `~/.deno` and `~/.cache/deno` directories don't even exist yet.

Anyway...

```
$ deno install --allow-net --reload --unstable https://deno.land/x/vno/install/vno.ts
[snip]
error: Uncaught SyntaxError: The requested module 'https://cdn.esm.sh/v15/_node_fs.js' does not provide an export named 'default'
import __fs$ from "https://cdn.esm.sh/v15/_node_fs.js";
       ~~~~~
    at <anonymous> (https://raw.githubusercontent.com/crewdevio/vue-deno-compiler/master/src/postcss/postcss.js:6:8)
```

**Comment by ije** [comment]
@vincent-olivert-riera sorry seems **vue-deno-compiler** download the cdn code of esm.sh, but esm.sh do some breaking changes for deno polyfills...

**Comment by vincent-olivert-riera** [comment]
It would be nice if the dependencies had pinned versions, so when you try to install `vno-1.2.1` (for instance) the versions of the dependencies are well known and not just the latest available. Otherwise problems like that one will keep happening.

**Comment by ije** [comment]
@vincent-olivert-riera you are totally right, esm.sh has changed the polyfills to versioned url, that means each version files will be stored forever

**Comment by buttercubz** [comment]
`vue-deno-compiler` is fixed try using `--reload`
